### ISSUE TITLE
Mpris extension resets the volume to zero

### ISSUE THREAD

**Issue by amanteaux** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#23]
**Describe the bug**

When the Mpris extension is used, the volume of each media player is set to zero when it starts playing a media. This behavior:
- is not present before the installation of the Mpris extension
- is still present just after the Mpris extension is uninstalled
- is not present after the computer is restarted

**Steps To Reproduce:**

Rhythmbox:
1. I open Rhythmbox and starts playing music
2. for a demi second, the volume is set to the level it was the last time Rhythmbox was used
3. then after this demi second, the volume is set to 0

I have the same issue with VLC:
1. I open VLC and start playing a video
2. The sound is directly set to 0
3. I change the volume to 100
4. I close VLC
5. I open it again and start playing a video
6. The sound is reset again to 0

**Expected behavior**

The volume level should not be reset each time a media player is reopen.

**System Details (please complete the following information):**

 - **Extension version:** 12 I guess
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32 and 3.34.1 (and maybe older versions but I cannot be sure)
 - **Distro/Release:** Ubuntu 19.04 (and maybe older versions but I cannot be sure), Ubuntu 19.10, Debian testing
 - **List of other installed and enabled Extensions:** OpenWeather, Places Status Indicator, User Themes, Workspace Indicator

**Additional Notes:**

I guess this issue exists ever since the first release of this extension. Before the Mpris extension, the "gnome-shell-extensions-mediaplayer" did not have this issue. I noticed this some months ago when I switched to the Mpris extension, but I did not get the time to investigate it before.

**Comment by JasonLG1979** [comment]
Yep, I can confirm with VLC. I know what the problem is and I think I can fix it.

The cause:

1st a little bit of background. Volume is a read/write MPRIS property. Unfortunately it's broken in at least a few players (Spotify for example) and there's no real good way to tell if it really works other than to poke the property and see if it causes the player to emit a property changed signal. Basically I read the property change it by +/-0.1 and then change it back to it's initial amount when the MPRIS interface shows up. (I do the same thing with the shuffle and repeat for the same reason) Normally that works fine but from I can tel VLC makes the interface available before fully populating the props or wiring up the getters or whatever. Basically it creates an empty interface at 1st. So no matter what when the interface shows up it shows up with a volume of 0 for that split sec I'm trying to read the volume.

I'll try delaying the poke to see if I wait like a sec that the props will be wired up.

**Comment by JasonLG1979** [comment]
Well after further investigation I've noticed that both VLC and Rhythmbox always start with the Volume at zero regardless if this extension is enabled or not. The default behavior seems to be to set the volume to the remembered value until playback is 1st initiated.

You can test this by disabling the extension and setting either player's volume to what ever you like while they are playing and close the player. Restart the player and either one's volume will be zero until you start playback.

So poking the props has nothing to do with the zero volume.

**Comment by JasonLG1979** [comment]
Although the delay is still probably still a good idea although it doesn't change anything for these particular players.

**Comment by JasonLG1979** [comment]
![ezgif-2-31825def4172](https://user-images.githubusercontent.com/6667703/68553170-7ba41880-03e4-11ea-88be-d839d2a08bf6.gif)

**Comment by JasonLG1979** [comment]
![ezgif-2-de180f363616](https://user-images.githubusercontent.com/6667703/68553252-359b8480-03e5-11ea-9abe-b3cbd7b5132d.gif)

**Comment by JasonLG1979** [comment]
Restarting my computer after disabling or uninstalling the extension does not have any effect on the behavior even with the extension is uninstalled. I wouldn't expect it to either. Functionally disabling the extension is about same as not having it installed at all. When it's disabled everything is disconnected and destroyed if it were ever enabled in the 1st place otherwise nothing was actually really executed. init, the function executed when extensions are read at startup does very little. All it does is load a couple icons and set up (as of yet non-existent) translations.

**Comment by amanteaux** [comment]
Thank you a lot for your quick investigation and for the fix!
I'll try this during this week!
