### ISSUE TITLE
Indicator icons

### ISSUE THREAD

**Issue by MichielJ1998** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#36]
**Describe the bug**

It's not really a bug I guess, neither an idea for extra features. In my current theme all the icons in the top panel are displayed in light grey. The icons of this extension are displayed in a darker grey. (see image)

**Expected behavior**

From where are the icons fetched? If I know where the icons are located, I can manually edit them. Another option is that you tell me where the gicon's are assigned for the top panel icon in the code. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33574375/82759101-4644a280-9deb-11ea-8450-bf175372795d.png)

Thanks in advance!

**Comment by JasonLG1979** [comment]
That's because the official version of Spotify does not include a symbolic icon. That is the full color icon desaturated, made grayscale. By default the panel does the same to any app without a symbolic icon. Google Chrome is another example. The extension follows suit to match the rest of the panel.
![gh3](https://user-images.githubusercontent.com/6667703/82768066-12b94680-9df2-11ea-8236-1e008d6c5b75.png)

I like things to match also, that's why [I added a symbolic icon in the unofficial flatpak package.](https://github.com/flathub/com.spotify.Client/commit/a1457b1bab5987f71245b87e42e0d90efe077370)
![gh1](https://user-images.githubusercontent.com/6667703/82768152-d2a69380-9df2-11ea-99f0-539bd14040c9.png)
![gh2](https://user-images.githubusercontent.com/6667703/82768153-d33f2a00-9df2-11ea-8434-38ff22c1c36e.png)
