### ISSUE TITLE
Center the controls under the button

### ISSUE THREAD

**Issue by aquatix** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#5]
## Distro Name & Version
Ubuntu Gnome 18.10. (Soon to be upgraded to 19.04 with 3.32).

## GNOME Shell Version
3.30.

## Expected Behavior

When clicking the button, open the little window with the play controls centered under it, so the user only has to move the mouse pointer a bit down to play/pause.

## Current Behavior

Currently, there is an offset, especially when the button is located a bit to the left in the bar because there are some other indicators already there (for example a system-monitor). So, when I click the button, right down from the mouse pointer the leftmost border of the controls window appears, and I have to move the pointer 'quite a bit' to actually click the pause button.

## Detailed Description

See above :)

Thanks for supporting 3.32! Came here after seeing the Media Player Indicator being unsupported from now on.

**Comment by JasonLG1979** [comment]
If I understand you want the menu to be centered with the indicator icon?

Open ~/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/extension.js in a text editor and change 0.0 to .05 line 443 and reload the shell and tell me if this has the desired effect.

Like this:

```js
super._init(0.5, "Mpris Indicator Button", false);
```
Note that the menu is a set width (as decided by the theme's "aggregate-menu" style class) and still not guaranteed to be centered if there is not enough screen space to the right of the indicator to be centered. For example if the menu is 400px wide but the center of the indicator icon is only 150px from the right edge of the screen it will still not be centered because there is not enough room.

In any event you don't have to actually open the menu at all to control the current active player. (the player who's icon is currently shown in the panel).

https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/wiki/User-Guide
