### ISSUE TITLE
Looking for Gnome 3.30 compatible release...

### ISSUE THREAD

**Issue by electriceccentric** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#51]
I know it's a long shot but would anyone happen to have this version? I'm using the retired version of this extension usually with both Spotify and VLC open and for some reason it captures VLC even with the dbus setting turned off. I wanted to see if the new version will only show Spotify so my media player buttons only control it and not VLC if it was the last active/focused.

**Comment by JasonLG1979** [comment]
3.30 is over 2 years old at this point. This extension uses a rolling release model. I generally only support the most current stable release because GNOME Shell offers no backwards compatibility release to release and extension tend to break with almost every release as a result. The only reason I'm even supporting both 3.38 and 40 at the moment is that Ubuntu 21.04 is stuck on 3.38 and the only required change to support both versions is a version bump in the metadata. Otherwise I would have dropped 3.38 support as soon as 40 was released if any code changes were required for the extension to work with 40.

**Comment by shooter0106** [comment]
If gnome 3.30 is still actual in 2022(thanks to Debian team), you can use `d8b2f10d9f6d9f91a078bc86cdc3b5c57f94f3c3` revision.
