### ISSUE TITLE
does not work in Gnome 43

### ISSUE THREAD

**Issue by ChrisLauinger77** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#67]
Hi,

loading the extension results in an error in gnome 43. Unfortunaty - the extension is great !

![Bildschirmfoto vom 2022-09-30 19-56-42](https://user-images.githubusercontent.com/3518684/193329157-99b741d5-8551-4b99-af4f-43f6371b15b1.png)

**Comment by JasonLG1979** [comment]
I saw that coming. It's been a few releases since anything broke and they changed the agg menu a lot with 43. I used the agg layout to make the menu widget the same width as the agg menu. I'll have to see what they're doing now.

I've got other things on my plate at the moment so I'll probably release a version for 43 as soon as Fedora 37 is released.

**Comment by Scotty-Trees** [comment]
Love you extension, been using it for a couple releases now. Looking to update to Fedora 37 or Ubuntu 22.10 since both are being released this week, so looking forward to seeing this extension gain Gnome 43 support in the future. Good luck with the coding and as a very grateful user, I just want to say thanks for making an awesome little extension I can't live with. Cheers

**Comment by JasonLG1979** [comment]
Thanks. With the whole new look of 43 I'll probably take the opportunity freshen up the look of the extension to match as much as possible.

**Comment by stdevPavelmc** [comment]
Looking forward for support, great extension!

**Comment by JasonLG1979** [comment]
I'm getting there. It looks horrible ATM, but at least it doesn't crash. It may take a bit to update everything to the look and feel of GNOME 43.

**Comment by stdevPavelmc** [comment]
Thanks!

**Comment by Scotty-Trees** [comment]
Just curious, any chance maybe we could see any WIP screenshots or screencasts of the extension update coming along? I'm very much missing this extension on Fedora 37! :)

**Comment by JasonLG1979** [comment]
PR's are always welcome.

**Comment by ChrisLauinger77** [comment]
PR #69 is there - I will test it today

**Comment by richo67** [comment]
Any progress? It is pity that it is not working on latest GNOME

**Comment by toupeira** [comment]
If anybody's looking for alternatives, I went with https://extensions.gnome.org/extension/4470/media-controls/ which works great in Gnome 43.

**Comment by ChrisLauinger77** [comment]
> If anybody's looking for alternatives, I went with https://extensions.gnome.org/extension/4470/media-controls/ which works great in Gnome 43.

I also switched to that one. It has some neat settings to customize it

**Comment by richo67** [comment]
Excellent, thank you!
