### ISSUE TITLE
Doesn't work with yandex music flatpak.

### ISSUE THREAD

**Issue by napalm79** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#9]
## Distro Name & Version
Ubuntu 18.04 LTS 
## GNOME Shell Version
3.28.3
## Other Installed Extensions
Dash to Panel  
Drop Down Terminal X
OpenWeather  
User Themes  
Workspace Indicator
## Expected Behavior
Indicator should appear in tray

## Current Behavior
Indicator does not appear in tray. It works with VLC though

**Comment by JasonLG1979** [comment]
I installed yandex music following these instructions:
https://nuvola.tiliado.eu/app/yandex_music/other/

It seems to work fine for me on GNOME Shell 3.32 (Fedora 30)?
![Screenshot from 2019-05-13 12-23-13](https://user-images.githubusercontent.com/6667703/57641188-03b27e00-757a-11e9-9b36-a26c8c140ebd.png)

The version of the extension you're using is rather old. Either it's a bug in that version of the extension or a bug in the version of the yandex music web app you're using. either way whatever the problem was seems to have already been fixed.

**Comment by napalm79** [comment]
Sorry, didn't know it's a freemium app. my mistake. Thanks for your time.

**Comment by JasonLG1979** [comment]
> Sorry, didn't know it's a freemium app. MPRIS support was working due to trial period and was disabled when this period ended. Thanks for your time.

Nuvola Apps are freemium? Yandex music is a wrapper around the yandex website. It's all supposed to be open source. If so and you were so inclined there's nothing to stop you from ripping the bits out that make it freemium and enabling MPRIS.
